# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 071a8ca7fd57f2d9b0c3403db77b0c3d9fdb942e610959d749eb42fdb9995555061cffa044e62c0defce43355d2cd3752b671146dd1ac6486b2648a9098b304a

test:
  secret_key_base: 6ca8b7ddf8d6798be8e34163fdf087de7dddc76f64e3d70d7c57a57965da7ebf946eab57b85632191eaf32ff4289e40b72826b632912a47537afc7a629c654f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
